# This is a basic workflow to help you get started with Actions

name: Release Versioning

# Triggers the workflow on push or pull request
on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

defaults:
  run:
    working-directory: act_scripts

jobs:
  version_tag:
    runs-on: ubuntu-18.04
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      run: |
        python version_tagging.py



#
#    - name: Set Tag
#      working-directory: act_scripts
#      run: |
#        python ./act_scripts/version_tagging.py
